//
//  GifDetailPresenter.swift
//  GIPHY App
//
//  Created Baglan on 12/3/17.
//  Copyright © 2017 Baglan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GifDetailPresenter: GifDetailPresenterProtocol, GifDetailInteractorOutputProtocol {
  
  weak private var view: GifDetailViewProtocol?
  var interactor: GifDetailInteractorInputProtocol?
  private let router: GifDetailWireframeProtocol
  var giphy: GiphyEntity!
  
  init(interface: GifDetailViewProtocol, interactor: GifDetailInteractorInputProtocol?, router: GifDetailWireframeProtocol) {
    self.view = interface
    self.interactor = interactor
    self.router = router
  }
  
  func viewDidLoad() {
    view?.updateWithTitle(giphy.title)
    view?.showLoading()
    interactor?.loadGif(url: giphy.originalImgUrl!)
  }
  
  func didTapClose() {
    router.dismissScreen()
  }
  
  func gotGifData(_ gifData: Data) {
    if let image = UIImage.gif(data: gifData) {
      view?.hideLoading()
      view?.showGifImage(image)
    } else {
      view?.showError(message: Constants.unknownError)
    }
  }
  
  func gotError(error: Error) {
    if let giphyError = error as? GiphyError {
      switch giphyError {
      case .NoNetworkError:
        debugPrint("NO NETWORK")
        view?.showError(message: "NO NETWORK!")
      case .ResponseError:
        debugPrint("RESPONSE ERROR")
        view?.showError(message: "RESPONSE ERROR")
      }
    } else {
      debugPrint(error)
      view?.showError(message: error.localizedDescription)
    }
//    view?.showError(message: Constants.unknownError)
  }
}
