//
//  GifDetailProtocols.swift
//  GIPHY App
//
//  Created Baglan on 12/3/17.
//  Copyright © 2017 Baglan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

//MARK: Wireframe -
protocol GifDetailWireframeProtocol: class {
  func dismissScreen()
}
//MARK: Presenter -
protocol GifDetailPresenterProtocol: class {
  var interactor: GifDetailInteractorInputProtocol? { get set }
  
  func viewDidLoad()
  func didTapClose()
}

//MARK: Interactor -
protocol GifDetailInteractorInputProtocol: class {
  
  var presenter: GifDetailInteractorOutputProtocol?  { get set }
  
  func loadGif(url: String)
}

protocol GifDetailInteractorOutputProtocol: class {
  
  func gotGifData(_ gifData: Data)
  func gotError(error: Error)
}

//MARK: View -
protocol GifDetailViewProtocol: IndicatableView {
  
  var presenter: GifDetailPresenterProtocol?  { get set }
  
  func showGifImage(_ image: UIImage)
  func updateWithTitle(_ title: String?)
}
