//
//  GifDetailRouter.swift
//  GIPHY App
//
//  Created Baglan on 12/3/17.
//  Copyright © 2017 Baglan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GifDetailRouter: GifDetailWireframeProtocol {
  
  weak var viewController: UIViewController?
  
  static func createModule(giphy: GiphyEntity) -> UIViewController {
    // Change to get view from storyboard if not using progammatic UI
    let storyboard = UIStoryboard(name: "GifDetailStoryboard", bundle: nil)
    let view = storyboard.instantiateViewController(withIdentifier: "GifDetailViewController") as! GifDetailViewController
    let interactor = GifDetailInteractor()
    let router = GifDetailRouter()
    let presenter = GifDetailPresenter(interface: view, interactor: interactor, router: router)
    presenter.giphy = giphy
    
    view.presenter = presenter
    interactor.presenter = presenter
    router.viewController = view
    
    return view
  }
  
  func dismissScreen() {
    viewController?.presentingViewController?.dismiss(animated: true, completion: nil)
  }
}
