//
//  HomeProtocols.swift
//  GIPHY App
//
//  Created Baglan on 12/3/17.
//  Copyright © 2017 Baglan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import RxSwift

//MARK: Wireframe -
protocol HomeWireframeProtocol: class {
  
}
//MARK: Presenter -
protocol HomePresenterProtocol: class {
  
  var interactor: HomeInteractorInputProtocol? { get set }
  
  func bindSearchBar(_ searchBar: UISearchBar)
}

//MARK: Interactor -
protocol HomeInteractorOutputProtocol: class {
  
  /* Interactor -> Presenter */
}

protocol HomeInteractorInputProtocol: class {
  
  var presenter: HomeInteractorOutputProtocol?  { get set }
  
  /* Presenter -> Interactor */
  func searchGiphyWithQuery(_ query: String) -> Observable<[GiphyEntity]>
}

//MARK: View -
protocol HomeViewProtocol: IndicatableView {
  
  var presenter: HomePresenterProtocol?  { get set }
  
  /* Presenter -> ViewController */
  func updateWithItems(_ items: [CellPresentation])
}
