//
//  HomePresenter.swift
//  GIPHY App
//
//  Created Baglan on 12/3/17.
//  Copyright © 2017 Baglan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import RxSwift


class HomePresenter: HomePresenterProtocol, HomeInteractorOutputProtocol {
  
  weak private var view: HomeViewProtocol?
  var interactor: HomeInteractorInputProtocol?
  private let router: HomeWireframeProtocol
  
  init(interface: HomeViewProtocol, interactor: HomeInteractorInputProtocol?, router: HomeWireframeProtocol) {
    self.view = interface
    self.interactor = interactor
    self.router = router
  }
  
  func viewDidLoad() {
    
  }
  
}
