//
//  HomeProtocols.swift
//  GIPHY App
//
//  Created Baglan on 12/3/17.
//  Copyright © 2017 Baglan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import RxSwift

//MARK: Wireframe -
protocol HomeWireframeProtocol: class {
  func showGifDetails(giphy: GiphyEntity)
}
//MARK: Presenter -
protocol HomePresenterProtocol: class {
  
  var interactor: HomeInteractorInputProtocol? { get set }
  
  func bindSearchBar(_ searchBar: UISearchBar)
  func selectedGiphyAt(index: Int)
}

protocol HomeInteractorInputProtocol: class {
  var presenter: HomeInteractorOutputProtocol? { get set }
  
  func searchGiphyWithQuery(_ query: String) -> Observable<[GiphyEntity]>
}

protocol HomeInteractorOutputProtocol: class {
  
  func gotError(error: Error)
}

//MARK: View -
protocol HomeViewProtocol: IndicatableView {
  
  var presenter: HomePresenterProtocol?  { get set }
  
  /* Presenter -> ViewController */
  func updateWithItems(_ items: [CellPresentation])
  func setLoadingState()
  func setInitialState()
  func setNothingFoundState()
}
