//
//  HomeInteractor.swift
//  GIPHY App
//
//  Created Baglan on 12/3/17.
//  Copyright © 2017 Baglan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import RxSwift


class HomeInteractor: HomeInteractorInputProtocol {
  
  func searchGiphyWithQuery(_ query: String) -> Observable<[GiphyEntity]> {
    return Observable.create({ (observer) -> Disposable in
      let request = GiphyService.searchForQuery(query, offset: nil, completion: { (networkResult) in
        switch networkResult {
        case .Success(let giphyArray):
          observer.onNext(giphyArray)
        case .Failure(let error):
          observer.onError(error)
        }
      })
      return Disposables.create {
        request.cancel()
      }
    })
  }
}
