//
//  HomeViewController.swift
//  GIPHY App
//
//  Created Baglan on 12/3/17.
//  Copyright © 2017 Baglan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeViewController: UIViewController, HomeViewProtocol {
  
  var presenter: HomePresenterProtocol?
  
  fileprivate let searchBar = UISearchBar()
  
  override func viewDidLoad() {
    super.viewDidLoad()
    
    initViews()
    presenter?.viewDidLoad()
  }
  
  private func initViews() {
    navigationItem.title = Constants.NavigationTitles.home
    if #available(iOS 11.0, *) {
      navigationController?.navigationBar.prefersLargeTitles = true
    }
    searchBar.placeholder = "Введите слово"
    searchBar.autocapitalizationType = .none
    navigationItem.titleView = searchBar
  }
  
}
