//
//  HomeProtocols.swift
//  GIPHY App
//
//  Created Baglan on 12/3/17.
//  Copyright © 2017 Baglan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HomeWireframeProtocol: class {
  
}
//MARK: Presenter -
protocol HomePresenterProtocol: class {
  
  var interactor: HomeInteractorInputProtocol? { get set }
  
  func viewDidLoad()
}

//MARK: Interactor -
protocol HomeInteractorOutputProtocol: class {
  
  /* Interactor -> Presenter */
}

protocol HomeInteractorInputProtocol: class {
  
  var presenter: HomeInteractorOutputProtocol?  { get set }
  
  /* Presenter -> Interactor */
}

//MARK: View -
protocol HomeViewProtocol: IndicatableView {
  
  var presenter: HomePresenterProtocol?  { get set }
  
  /* Presenter -> ViewController */
}
